apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: executor-app
  template:
    metadata:
      labels:
        app: executor-app
    spec:
      containers:
      - name: executor-app
        image: gcr.io/animax-423606/executor:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "4"
#        volumeMounts:
#        - name: example-storage
#          mountPath: /mnt/data
#      volumes:
#      - name: example-storage
#        persistentVolumeClaim:
#          claimName: example-pvc
      imagePullSecrets:
      - name: gcr-json-key
